version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install HTML Tidy
      - yum update -y
      - yum install -y tidy
  build:
    commands:
      # Use HTML Tidy to check and fix the HTML files in the source directory
      - tidy -im -asxhtml -utf8 -w 120 -q -e -access 0 source/*.html
      # Copy the HTML files to the output directory
      - cp source/*.html output/
artifacts:
  files:
    # Include
