version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install pytidylib
  build:
    commands:
      - python tidy.py
artifacts:
  files:
    - '**/*'
  base-directory: output
